### ISSUE TITLE
Editing a post requires re-selecting hub

### ISSUE THREAD

**Issue by yattias** [ResearchHub/issues#1]
1. Click edit post
2. Click republish
3. You will see the hub is missing title. You will need to x out of it and reenter the hub associated with the post

![Image](https://github.com/ResearchHub/researchhub-web/assets/802819/d27a4887-d24f-4ca6-9c80-0cb5acf7cb20)

**Comment by yattias** [comment]
@dominikusbrian Let us know if you intend to submit a PR for this soon. This one is a bit high priority and something we would like to resolve this sprint

**Comment by dominikusbrian** [comment]
@yattias would love to start looking into this and working on a PR submission. What's the ideal timeline for this sprint ? How soon ?

**Comment by yattias** [comment]
Hey @dominikusbrian can you work on this in the coming days? If not, no worries I will tackle this. Looking to have this completed by Tuesday
