### ISSUE TITLE
New reputation algorithm

### ISSUE THREAD

**Issue by yattias** [ResearchHub/issues#16]
- [ ] Create rep "bins" (or tiers) for reputation. These bins should be associated with a hub
       ℹ️ We discussed rep be associated with a subfield but in actuality, there will be a hub created for each of these subfields (see https://github.com/ResearchHub/issues/issues/12)
- [ ] Implement point system (e.g. citation = 1000 points)
- [ ] Identify triggers that should recalculate reputation
- [ ] Create script to recalculate rep for each author (not user)
- [ ] Every rep should be associated with some hub. In a case where that is not possible for some reason, we should associated it with a default generic hub

Example provided by Tyler:
[CellBio_REPTiersCalcs.pptx](https://github.com/user-attachments/files/15534888/CellBio_REPTiersCalcs.pptx)

**Comment by joycesticks** [comment]
Tyler will get a python script and/or a loom video instruction in order to help leverage the community to manually assign the buckets for each subfield 

Ideally we can get this done by: 6/21

**Comment by koutst** [comment]
<img width="947" alt="Screenshot 2024-06-06 at 5 13 11 PM" src="https://github.com/ResearchHub/issues/assets/17444861/7d493069-4e3d-4f3c-857d-88e2b3171e07">

After speaking with @yattias it seems we will eventually like a view like this for reputation. I know this has been discussed extensively but is there a way to implement things which has a consistent value across all citations? It could make a page like this more intuitive. We could then have bins which will be comparable across subfields. 

Also, having one value that varies per subfield (bins) versus two (bins and amount per citation per bin) would simplify the implementation.

**Comment by koutst** [comment]
We agreed that the current approach is the best way forward to make sure we have an upvote that contributes appropriately to the reputation score.

**Comment by yattias** [comment]
@TylerDiorio I think given the new direction we will need buckets and mapping for each subfields

**Comment by yattias** [comment]
@koutst we should also chat about the data structure that will be provided to the client in order to build this:

https://github.com/orgs/ResearchHub/projects/3/views/3?pane=issue&itemId=65910281

**Comment by TylerDiorio** [comment]
Ran into some rate limits when trying to pull >100K papers from OpenAlex's web client (https://openalex.org/works) so I'm processing their snapshot on my local PC to get these bins. I'm parsing the time-sorted "Works" into separate .jsonl files for each subfield so we can more easily use this in the future. The snapshot "Works" folder has >360GB (.gz compressed) .jsonl files for all papers, looks like it might take around 15-20 hours to process into those separate .jsonl files on my PC. I should be able to get the bins by this weekend.

Script (process snapshot locally): 
[Works2Subfields.py.zip](https://github.com/user-attachments/files/15831585/Works2Subfields.py.zip)
