### ISSUE TITLE
Create initial Stripe webhook implementation

### ISSUE THREAD

**Issue by gzurowski** [ResearchHub/issues#163]

**Comment by dominikusbrian** [comment]
Related to this, the checkout function for ResearchHub Journal Publication doesn't seems to work properly. 
Got the following error when trying to checkout for paying APC.
![image](https://github.com/user-attachments/assets/616dcd36-0671-458a-8cb0-88b373362c5d)
running on chrome browser

**Comment by gzurowski** [comment]
@dominikusbrian This should be resolved now.
