### ISSUE TITLE
Z-index issue (comment shows above header)

### ISSUE THREAD

**Issue by yattias** [ResearchHub/issues#3]
Picture worth a thousand words
https://www.researchhub.com/post/2170/anonymity-in-peer-review

![image](https://github.com/ResearchHub/researchhub-web/assets/802819/bca1d7d3-d722-4944-ab82-30e5d9b9e73f)

**Comment by lightninglu10** [comment]
Fix here: https://github.com/ResearchHub/researchhub-web/pull/1754
