### ISSUE TITLE
Design: Profile page design requirements 

### ISSUE THREAD

**Issue by yattias** [ResearchHub/issues#30]
### Reputation changes

After much debate, we landed on showing bars of reputation instead of the circular graphic.

![image](https://github.com/ResearchHub/issues/assets/802819/df277a20-c0ee-49a3-9f34-556a28e704b4)

Example from Mario Kart
![image](https://github.com/ResearchHub/issues/assets/802819/8f908134-6526-4d70-823f-6ae12ba2a44f)

### Remove Expertise section at bottom of page:

Instead of this section, we will pop open a modal when user clicks "show more" in the expertise block at the top. No need to design this modal, let's just remove this section from the design
![image](https://github.com/ResearchHub/issues/assets/802819/b1f34b29-8b6d-4ffb-8a57-d3ef0ab23759)

### Activity feed

One important section that is missing from the profile "overview" page is user activity. These are actions that user has taken on the site such as commenting or sharing a paper. Many new users would not have any papers created like authors so it is important that their homepage shows something

![image](https://github.com/ResearchHub/issues/assets/802819/a70043b6-5d25-408b-bb5c-387e185ee169)

![image](https://github.com/ResearchHub/issues/assets/802819/fc21b78f-80da-4c7e-8138-3f9131bafc41)

### Move contribution graph up higher

I think it may show more color or excitement if we move this up higher by a bit. Maybe above top works?

![image](https://github.com/ResearchHub/issues/assets/802819/302fec6c-7479-4738-ba90-7882d644e394)

### Update cards to include avatars
We want every name in our site to include an avatar next to it. If multiple authors, avatars should be "piled up"

![image](https://github.com/ResearchHub/issues/assets/802819/ed2c1fdf-faa1-4a7a-8ca7-1966bca8d4b7)

And in feed page:

![image](https://github.com/ResearchHub/issues/assets/802819/10200707-9347-439a-b83d-e94740feab13)

### Claim profile
This modal looks kinda weird. Maybe because content is centered?

![image](https://github.com/ResearchHub/issues/assets/802819/7cba5081-417a-42ec-9792-473383405901)

### Mobile designs

The mobile designs on figma are currently incomplete and do not include all of the components in the desktop version. This is expected. Once we figure out the above, we should move to mobile designs

**Comment by IshadP** [comment]
Hey! I am interested in designing these pages, can you assign it to me?
After I can help to complete mobile designs as well!

**Comment by yattias** [comment]
Hi @IshadP we already have a designer working on this ticket. You can check out https://github.com/ResearchHub/issues/issues/31 or https://github.com/ResearchHub/issues/issues/39 and design some wireframes or share some ideas
